version: "3.7"

services:
    server:
        container_name: person
        build: .
        ports:
            - "8080:8080"
        restart: on-failure
        volumes: 
            - api:/usr/src/app/
        networks: 
            - person
        depends_on: 
            - db
    db:
        container_name: persons_db
        build:
            context: ./dbfolder
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: person
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        ports: 
            - "3306:3306"
        tty: true
        volumes: 
            - database_mysql:/var/lib/mysql 
        networks: 
            - person    
volumes:
    api:
    database_mysql:
    
networks: 
    person:
        driver: bridge